"""Model registry sync: regenerate models.yaml from models.dev + serve overlay.

Layered sources (neutrality first, so the registry — and our
``ModelRef`` abstraction — is never stuck to one harness):
* **Base (models.dev)**: the neutral upstream registry. Every model
  id becomes a base row; every ``reasoning_options`` entry of type
  ``effort`` contributes its values as ``{id}+{variant}`` rows
  (verified 1:1 against serve-advertised variants where both
  declare them). ``toggle``/``budget_tokens`` types carry no
  variant names — they ride along as metadata only.
* **Serve overlay** (scratch ``opencode serve``): the local layer
  models.dev can never see — custom providers (``gmi``), built-ins
  (``ollama``), models the serve adds under known providers, and
  extra variants the serve invents (provider-level defaults like
  gmicloud/nvidia ``high/low/medium``, user customs). All appended
  after the base; never removes an upstream row.
* **Customs file** (``models.custom.yaml``, hand-maintained, merged
  at load by :class:`ConfigManager`): entries neither source has.
  Sync never touches it.

Plus a metadata sidecar (``models.meta.json``) per qualified id —
``variants``, ``reasoning_options``, ``limit``, ``modalities``,
``cost`` — for utilities (session budgets, price display). The
flat-string registry stays the picker/wire contract; metadata is
additive and optional.

``sweave models sync`` orchestrates: fetch models.dev (falls back
to serve-only generation with a warning when offline), scratch
serve, merge, diff, write. Output is deterministic; re-syncs are
no-op diffs. Refuses to write an empty registry. models.yaml is
read at server startup — restart afterwards.
"""

from __future__ import annotations

import json
import logging
import shutil
import socket
import subprocess
import tempfile
import time
import urllib.request
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

MODELS_DEV_URL = "https://models.dev/api.json"
MODELS_DEV_TIMEOUT_S = 120.0

HEADER_COMMENT = """\
# Sweave model registry — GENERATED by `sweave models sync` from
# models.dev (base) + a scratch `opencode serve` overlay (custom
# providers, serve-only models, extra variants). Do not hand-edit
# rows; re-run sync instead. Hand entries belong in
# models.custom.yaml (merged at load, never overwritten).
# Variant rows (`model+variant`, e.g. `inkling:free+low`) select an
# opencode reasoning-effort preset per turn; unsuffixed rows use the
# provider default. The running server reads this file at startup —
# restart it after syncing.
"""

CUSTOMS_FILENAME = "models.custom.yaml"
META_FILENAME = "models.meta.json"

SCRATCH_PORT_START = 18792
SCRATCH_PORT_TRIES = 8
SERVE_START_TIMEOUT_S = 30.0


def resolve_opencode_binary() -> str | None:
    """Return the opencode executable path, or None when absent."""
    return shutil.which("opencode")


def pick_free_port(start: int = SCRATCH_PORT_START, tries: int = SCRATCH_PORT_TRIES) -> int:
    """Find a free loopback port for the scratch serve."""
    for port in range(start, start + tries):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            try:
                sock.bind(("127.0.0.1", port))
            except OSError:
                continue
            return port
    raise RuntimeError(f"no free port in {start}..{start + tries - 1}")


def spawn_scratch_serve(opencode_bin: str, port: int) -> "subprocess.Popen":
    """Start an isolated ``opencode serve`` (scratch cwd, no project config)."""
    workdir = tempfile.mkdtemp(prefix="sweave-models-sync-")
    return subprocess.Popen(
        [opencode_bin, "serve", "--port", str(port), "--hostname", "127.0.0.1"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        cwd=workdir,
    )


def stop_scratch_serve(proc: "subprocess.Popen") -> None:
    """Terminate a scratch serve plus its child tree (best effort)."""
    import sys

    try:
        if sys.platform == "win32":
            # The .cmd wrapper drops the child on plain terminate;
            # kill the whole tree or the serve outlives the sync.
            subprocess.run(
                ["taskkill", "/PID", str(proc.pid), "/T", "/F"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=15,
            )
        else:
            proc.terminate()
    except Exception:  # noqa: BLE001
        pass


def fetch_models_dev(timeout_s: float = MODELS_DEV_TIMEOUT_S) -> dict:
    """Fetch the neutral upstream registry (4-5 MB of JSON)."""
    request = urllib.request.Request(
        MODELS_DEV_URL, headers={"User-Agent": "sweave-models-sync"}
    )
    with urllib.request.urlopen(request, timeout=timeout_s) as response:
        payload = json.loads(response.read())
    if not isinstance(payload, dict) or not payload:
        raise RuntimeError("models.dev returned an unrecognised payload")
    return payload


def fetch_serve_providers(port: int, timeout_s: float = SERVE_START_TIMEOUT_S) -> dict:
    """Poll the scratch serve until /config/providers answers.

    Normalizes both payload shapes into ``{provider_id: models}``.
    Raises on startup timeout or an unrecognised shape.
    """
    deadline = time.monotonic() + timeout_s
    last_error: Exception | None = None
    url = f"http://127.0.0.1:{port}/config/providers"
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=5) as response:
                payload = json.loads(response.read())
            return _normalize_providers(payload)
        except Exception as exc:  # noqa: BLE001
            last_error = exc
            time.sleep(0.5)
    raise RuntimeError(f"scratch serve did not answer {url}: {last_error}")


def _normalize_providers(payload: Any) -> dict:
    """Normalize a /config/providers payload to ``{provider_id: models}``."""
    providers = payload.get("providers", payload) if isinstance(payload, dict) else payload
    if isinstance(providers, list):
        providers = {
            item["id"]: item
            for item in providers
            if isinstance(item, dict) and item.get("id")
        }
    if not isinstance(providers, dict) or not providers:
        raise RuntimeError(
            f"unrecognised /config/providers shape: {str(payload)[:120]}"
        )
    out: dict[str, Any] = {}
    for provider_id, entry in providers.items():
        # Live provider objects always carry a "models" mapping.
        # Anything else is either a provider object without models
        # (contributes no rows — its id/name keys must never become
        # rows) or the legacy bare {model: entry} mapping (used
        # directly, e.g. in tests).
        if not isinstance(entry, dict):
            out[provider_id] = {}
        elif isinstance(entry.get("models"), dict):
            out[provider_id] = entry["models"]
        elif "id" in entry:
            out[provider_id] = {}
        else:
            out[provider_id] = entry
    if not any(out.values()):
        raise RuntimeError("no models found in /config/providers payload")
    return out


def effort_variants(entry: Any) -> list[str]:
    """Variant names declared by a models.dev model entry.

    Only ``effort`` options name selectable variants (verified 1:1
    against serve-advertised variants); ``toggle``/``budget_tokens``
    are capability metadata, not row suffixes.
    """
    variants: set[str] = set()
    if isinstance(entry, dict):
        for option in entry.get("reasoning_options") or []:
            if isinstance(option, dict) and option.get("type") == "effort":
                for value in option.get("values") or []:
                    if isinstance(value, str) and value and "/" not in value:
                        variants.add(value)
    return sorted(variants)


def serve_variants(entry: Any) -> list[str]:
    """Variant names advertised by a serve model entry."""
    if isinstance(entry, dict):
        variants = entry.get("variants")
        if isinstance(variants, dict):
            return sorted(v for v in variants if isinstance(v, str))
    return []


def build_upstream_registry(models_dev: dict[str, Any]) -> dict[str, list[str]]:
    """Build the deterministic base registry from models.dev.

    Pure function: providers sorted, models sorted, effort-derived
    variant rows appended per model (sorted). Non-dict entries
    contribute the base row only.
    """
    registry: dict[str, list[str]] = {}
    for provider_id in sorted(models_dev):
        models = models_dev[provider_id]
        if not isinstance(models, dict):
            continue
        rows: list[str] = []
        for model_id in sorted(models):
            rows.append(model_id)
            for variant in effort_variants(models[model_id]):
                rows.append(f"{model_id}+{variant}")
        if rows:
            registry[provider_id] = rows
    return registry


def build_registry(providers: dict[str, Any]) -> dict[str, list[str]]:
    """Build a registry from serve-shaped provider data (legacy helper).

    Kept for the serve-only fallback path and tests: every model id
    becomes a base row plus one row per advertised variant.
    Prefer :func:`build_upstream_registry` + :func:`apply_serve_overlay`.
    """
    registry: dict[str, list[str]] = {}
    for provider_id in sorted(providers):
        models = providers[provider_id]
        if not isinstance(models, dict):
            continue
        rows: list[str] = []
        for model_id in sorted(models):
            rows.append(model_id)
            for variant in serve_variants(models[model_id]):
                rows.append(f"{model_id}+{variant}")
        if rows:
            registry[provider_id] = rows
    return registry


def apply_serve_overlay(
    upstream: dict[str, list[str]], serve_models: dict[str, Any]
) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Append the serve-only layer onto the upstream registry.

    * providers the upstream lacks (customs, built-ins) are copied
      whole (base + serve-advertised variant rows)
    * models the upstream lacks under known providers are copied
    * serve variants missing upstream (provider defaults, user
      customs) become extra ``+variant`` rows
    Upstream rows are never removed. Returns ``(merged, overlay)``
    where ``overlay`` maps provider -> the rows the overlay added
    (for the sync summary).
    """
    merged: dict[str, list[str]] = {pid: list(rows) for pid, rows in upstream.items()}
    overlay: dict[str, list[str]] = {}
    upstream_models: dict[str, set[str]] = {
        pid: {row.rpartition("+")[0] if "+" in row and "/" not in row.rpartition("+")[2] else row for row in rows}
        for pid, rows in upstream.items()
    }
    # Base ids per provider for membership checks (variant rows
    # excluded so a model with only upstream variants still counts
    # as known).
    for provider_id in sorted(serve_models):
        models = serve_models[provider_id]
        if not isinstance(models, dict):
            continue
        added: list[str] = []
        if provider_id not in merged:
            merged[provider_id] = []
            upstream_models[provider_id] = set()
        known_rows = set(merged[provider_id])
        for model_id in sorted(models):
            if model_id not in upstream_models[provider_id]:
                # Serve-only model: base + advertised variants.
                for row in [model_id] + [
                    f"{model_id}+{variant}" for variant in serve_variants(models[model_id])
                ]:
                    if row not in known_rows:
                        merged[provider_id].append(row)
                        known_rows.add(row)
                        added.append(row)
                upstream_models[provider_id].add(model_id)
            else:
                # Known model: only genuinely new variants. The suffix
                # check mirrors parse_model_ref (a + whose tail holds
                # / belongs to the model id, not a variant).
                upstream_variants = set()
                prefix = model_id + "+"
                for row in merged[provider_id]:
                    if row.startswith(prefix) and "/" not in row[len(prefix):]:
                        upstream_variants.add(row[len(prefix):])
                for variant in serve_variants(models[model_id]):
                    row = f"{model_id}+{variant}"
                    if variant not in upstream_variants and row not in known_rows:
                        merged[provider_id].append(row)
                        known_rows.add(row)
                        added.append(row)
        # Keep rows sorted: base models alphabetical, variant rows
        # directly after their base (same order build_* produce).
        merged[provider_id].sort(key=_row_sort_key)
        if added:
            overlay[provider_id] = sorted(added)
    # Overlay providers were appended after the upstream block;
    # re-sort so provider order is deterministic AND alphabetical
    # (otherwise every sync shows a relocation diff).
    return {pid: merged[pid] for pid in sorted(merged)}, overlay


def _row_sort_key(row: str) -> tuple[str, str]:
    """Sort base rows alphabetically with variant rows after their base."""
    base, sep, variant = row.rpartition("+")
    if sep and variant and "/" not in variant:
        return (base, variant)
    return (row, "")


def build_metadata(
    models_dev: dict[str, Any], serve_models: dict[str, Any]
) -> dict[str, dict[str, Any]]:
    """Build the per-qualified-id metadata sidecar.

    Upstream declarations first (reasoning_options, limit,
    modalities, cost), unioned with serve-advertised variants and
    serve limit/cost/capabilities where upstream is silent. Keys
    are qualified ``provider/model`` ids.
    """
    meta: dict[str, dict[str, Any]] = {}
    for provider_id in sorted(set(models_dev) | set(serve_models)):
        up_models = models_dev.get(provider_id) or {}
        sv_models = serve_models.get(provider_id) or {}
        if not isinstance(up_models, dict):
            up_models = {}
        if not isinstance(sv_models, dict):
            sv_models = {}
        for model_id in sorted(set(up_models) | set(sv_models)):
            up_entry = up_models.get(model_id)
            sv_entry = sv_models.get(model_id)
            if not isinstance(up_entry, dict):
                up_entry = {}
            if not isinstance(sv_entry, dict):
                sv_entry = {}
            variants = sorted(set(effort_variants(up_entry)) | set(serve_variants(sv_entry)))
            entry: dict[str, Any] = {
                "provider": provider_id,
                "model": model_id,
                "variants": variants,
            }
            reasoning_options = up_entry.get("reasoning_options")
            if reasoning_options:
                entry["reasoning_options"] = reasoning_options
            limit = up_entry.get("limit") or sv_entry.get("limit")
            if limit:
                entry["limit"] = limit
            modalities = up_entry.get("modalities")
            if modalities:
                entry["modalities"] = modalities
            cost = up_entry.get("cost") or sv_entry.get("cost")
            if cost:
                entry["cost"] = cost
            capabilities = sv_entry.get("capabilities")
            if capabilities:
                entry["capabilities"] = capabilities
            meta[f"{provider_id}/{model_id}"] = entry
    return meta


def merge_custom_rows(
    registry: dict[str, list[str]], customs: dict[str, Any] | None
) -> dict[str, list[str]]:
    """Merge the hand-maintained customs file (additive, deduped)."""
    if not customs:
        return registry
    merged: dict[str, list[str]] = {pid: list(rows) for pid, rows in registry.items()}
    providers = customs.get("providers") or {}
    for provider_id in sorted(providers):
        rows = providers[provider_id] or []
        known = set(merged.get(provider_id, []))
        merged.setdefault(provider_id, [])
        for row in rows:
            if isinstance(row, str) and row not in known:
                merged[provider_id].append(row)
                known.add(row)
        merged[provider_id].sort(key=_row_sort_key)
    return merged


def strip_variant_rows(registry: dict[str, list[str]]) -> dict[str, list[str]]:
    """Drop ``+variant`` rows, keeping base model rows.

    Variants are a per-turn selection dimension (separate dropdown
    fed by the metadata sidecar), not separate registry entries —
    the picker lists each model once. Pure function.
    """
    stripped: dict[str, list[str]] = {}
    for provider_id in sorted(registry):
        base_rows = [
            row
            for row in registry[provider_id]
            if not _row_sort_key(row)[1]
        ]
        if base_rows:
            stripped[provider_id] = base_rows
    return stripped


def diff_registries(
    old: dict[str, list[str]], new: dict[str, list[str]]
) -> dict[str, dict[str, list[str]]]:
    """Per-provider added/removed row sets (for the sync summary)."""
    summary: dict[str, dict[str, list[str]]] = {}
    for provider in sorted(set(old) | set(new)):
        before = set(old.get(provider, []))
        after = set(new.get(provider, []))
        summary[provider] = {
            "added": sorted(after - before),
            "removed": sorted(before - after),
        }
    return summary


def ensure_nonempty(registry: dict[str, list[str]]) -> None:
    """Refuse an empty registry (writing it would wipe models.yaml)."""
    if not registry or not any(registry.values()):
        raise RuntimeError(
            "refusing to write an empty registry — no providers/models "
            "resolved; models.yaml left untouched"
        )


def write_registry(path: Path, providers: dict[str, list[str]], default: str | None) -> None:
    """Write models.yaml (UTF-8, no BOM; header comment + payload).

    Never via shell redirection (UTF-16 LE + BOM breaks PyYAML) —
    always through this writer.
    """
    import yaml

    payload: dict[str, Any] = {"models": {"providers": providers}}
    if default:
        payload["models"]["default"] = default
    text = HEADER_COMMENT + yaml.safe_dump(
        payload, sort_keys=False, allow_unicode=True
    )
    path.write_text(text, encoding="utf-8")


def write_metadata(path: Path, meta: dict[str, dict[str, Any]]) -> None:
    """Write the metadata sidecar (UTF-8 JSON, sorted keys)."""
    path.write_text(
        json.dumps(meta, indent=1, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def sync_registry(
    registry_path: Path,
    *,
    port_start: int = SCRATCH_PORT_START,
    include_all_upstream: bool = False,
    include_variant_rows: bool = False,
    on_event: Any = None,
) -> dict[str, Any]:
    """Run the full sync: models.dev + serve overlay -> write.

    Scope: by default only providers already in the registry file
    plus providers the serve reports (newly configured customs are
    picked up; the undiscovered upstream universe stays out — a
    213-provider dump is not a curated registry). Pass
    ``include_all_upstream=True`` (``--all``) for the full dump.

    Variant rows (``model+variant``) are OFF by default: reasoning
    effort is a separate dropdown fed by the metadata sidecar, not
    multiplied registry entries. Pass ``include_variant_rows=True``
    (``--with-variants``) to restore the expanded rows. The sidecar
    always carries the full variant lists either way.

    Returns a report dict (providers, models, variant_rows, added,
    removed, upstream_only flag, default_kept, pid). Raises on
    binary/serve failures; the registry file is only touched after
    a successful fetch + build + non-empty guard. When models.dev
    is unreachable, falls back to serve-only generation (the old
    behaviour) with a warning instead of failing.
    """
    emit = on_event or (lambda _msg: None)
    binary = resolve_opencode_binary()
    if not binary:
        raise RuntimeError("opencode executable not found on PATH")
    port = pick_free_port(port_start)
    emit(f"starting scratch opencode serve on 127.0.0.1:{port}")
    proc = spawn_scratch_serve(binary, port)
    try:
        serve_models = fetch_serve_providers(port)
    finally:
        stop_scratch_serve(proc)

    import yaml

    current_text = registry_path.read_text(encoding="utf-8") if registry_path.exists() else ""
    current_data = yaml.safe_load(current_text) or {} if current_text else {}
    current_models = (current_data.get("models") or current_data) if isinstance(current_data, dict) else {}
    old_registry: dict[str, list[str]] = {
        provider: list(models or [])
        for provider, models in (current_models.get("providers") or {}).items()
    }
    old_default = current_models.get("default")

    try:
        emit("fetching models.dev upstream (4-5 MB)")
        models_dev_raw = fetch_models_dev()
        models_dev = {
            pid: entry.get("models", {})
            for pid, entry in models_dev_raw.items()
            if isinstance(entry, dict)
        }
        if not include_all_upstream:
            # Curated scope: keep the registry's existing providers
            # plus anything the serve reports (new customs surface
            # automatically); the undiscovered upstream stays out.
            scope = set(old_registry) | set(serve_models)
            models_dev = {pid: models_dev[pid] for pid in sorted(scope) if pid in models_dev}
            serve_models = {pid: serve_models[pid] for pid in sorted(scope) if pid in serve_models}
        upstream_registry = build_upstream_registry(models_dev)
        new_registry, overlay = apply_serve_overlay(upstream_registry, serve_models)
        meta = build_metadata(models_dev, serve_models)
        source = "models.dev+serve"
    except Exception as exc:  # noqa: BLE001
        emit(f"warning: models.dev unreachable ({exc}); falling back to serve-only")
        new_registry = build_registry(serve_models)
        overlay = {}
        meta = build_metadata({}, serve_models)
        source = "serve-only-fallback"
    ensure_nonempty(new_registry)
    if not include_variant_rows:
        new_registry = strip_variant_rows(new_registry)
        ensure_nonempty(new_registry)

    diff = diff_registries(old_registry, new_registry)
    added = sum(len(v["added"]) for v in diff.values())
    removed = sum(len(v["removed"]) for v in diff.values())

    default_kept = True
    if old_default:
        flat = {row for rows in new_registry.values() for row in rows}
        # The default may be stored qualified (provider/model) while
        # the registry holds bare ids; compare both shapes.
        bare_default = old_default.split("/", 1)[1] if "/" in old_default else old_default
        if old_default not in flat and bare_default not in flat:
            default_kept = False

    write_registry(registry_path, new_registry, old_default)
    meta_path = registry_path.with_name(META_FILENAME)
    write_metadata(meta_path, meta)
    n_variants = sum(
        1 for rows in new_registry.values() for row in rows
        if _row_sort_key(row)[1]
    )
    overlay_rows = sum(len(rows) for rows in overlay.values())
    return {
        "providers": len(new_registry),
        "models": sum(len(rows) for rows in new_registry.values()),
        "variant_rows": n_variants,
        "added": added,
        "removed": removed,
        "diff": diff,
        "overlay_rows": overlay_rows,
        "overlay": overlay,
        "default": old_default,
        "default_kept": default_kept,
        "source": source,
        "meta_path": str(meta_path),
        "meta_entries": len(meta),
        "path": str(registry_path),
    }
